version: '3.7'

name: hello-login

services:

  wordpress:
    image: wordpress:6.2.1
    restart: always
    depends_on:
      - db
      - mailhog
    ports:
      - '8080:80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: hellouser
      WORDPRESS_DB_PASSWORD: hellopass
      WORDPRESS_DB_NAME: hellodb
      SMTP_HOST: mailhog
      SMTP_PORT: 1025

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: hellodb
      MYSQL_USER: hellouser
      MYSQL_PASSWORD: hellopass
      MYSQL_ROOT_PASSWORD: hellodbrootpassword

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - '8081:80'
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: hellodbrootpassword
      MYSQL_USER: hellouser
      MYSQL_PASSWORD: hellopass

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - '8025:8025' # web interface
      # - '1025:1025' # SMTP
