version: '3.7'

services:

  hello_wordpress:
    image: wordpress
    restart: always
    depends_on:
      - hello_db
      - hello_mailhog
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: hello_db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      SMTP_HOST: hello_mailhog
      SMTP_PORT: 1025

  hello_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

  hello_mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - 8025:8025 # web interface
      - 1025:1025 # SMTP
